/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Uranaishi;

import Uranaishi.lib.*;

public class App {
    public static void main(String[] args) {
        Node stima = new Node("Stima"),
             matdis = new Node("Matdis"),
             kalkulus = new Node("Kalkulus");

        Graph g1 = new Graph(stima, matdis, kalkulus);

        g1.addEdge(stima, matdis);
        g1.addEdge(stima, kalkulus);
        g1.addEdge(matdis, kalkulus);

        g1.print();
    }
}
